version: '3.8'


services:


  example-frontend:
    build: ./example-frontend  
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
      - REACT_APP_BACKEND_URL=http://localhost/8080
    container_name: example-frontend
    networks:
      - nginx-network

  postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres
    networks:
      - nginx-network
      
  example-backend:
    build: ./example-backend
    container_name: example-backend
    restart: unless-stopped
    environment:
      - REQUEST_ORIGIN=http://localhost/
      - REQUEST_ORIGIN=http://localhost:5000
      - REQUEST_ORIGIN=http://127.0.0.0
      - PORT=8080
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    networks:
      - nginx-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nginx-network

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./example-backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx
    
    depends_on:
      - example-backend
    networks:
      - nginx-network

networks:
  nginx-network: 
    name: nginx-network

#version: '3.8'
#
#services:
#  postgres:
#    image: postgres
#    restart: unless-stopped
#    environment:
#      - POSTGRES_DATABASE=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - ./database:/var/lib/postgresql/data
#    container_name: postgres
#    networks:
#      - nginx-network
#
#  nginx:
#    image: nginx:1.27.0-alpine
#    container_name: nginx
#    volumes:
#      - ./example-backend/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - nginx-network
#    depends_on:
#      - backend
#    ports:
#      - 80:80
#
#  backend:
#    build: ./example-backend
#    # ports:
#    #   - 8080:8080
#    environment:
#      - REDIS_HOST=redis
#      - POSTGRES_HOST=postgres
#      - POSTGRES_DATABASE=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - postgres
#    networks:
#      - nginx-network
#
#  frontend:
#    build: ./example-frontend
#    # ports:
#    #   - 5000:5000
#    networks:
#      - nginx-network
#
#  redis:
#    image: redis:7.0.15-alpine
#    ports:
#      - 6379:6379
#    networks:
#      - nginx-network
#
#networks:
#  nginx-network:
#    name: nginx-network