version: '3.8'


services:

  example-backend:
    image: example-backend
    container_name: example-backend
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - REQUEST_ORIGIN=http://localhost/
      - REQUEST_ORIGIN=http://localhost:5000
      - REQUEST_ORIGIN=http://127.0.0.0
      - PORT=8080
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - postgres
    networks:
      - nginx-network

  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
      - REACT_APP_BACKEND_URL=http://localhost/5000
    container_name: example-frontend
    networks:
      - nginx-network
  postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres
    networks:
      - nginx-network
      
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - nginx-network

  nginx:
    image: nginx
    volumes:
      - ./example-backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network